#!/bin/bash
sudo yum update -y
sudo yum install -y httpd
sudo systemctl start httpd
sudo systemctl enable httpd
echo "<h1>Welcome to My Highly Available Web App - Instance 1</h1>" | sudo tee /var/www/html/index.html
